### ISSUE TITLE
Blacklist common louds

### ISSUE THREAD

**Issue by josiahp** [desert-planet/hayt#168]
Hayt shouldn't remember common louds, such as 'IIRC'. I haven't looked at the code enough to suggest an implementation.

**Comment by drobati** [comment]
We could add a simple syntax like `!IIRC` to ban entries, storing them in a separate store to be validated against.

**Comment by drobati** [comment]
First, louds supports deleting. `.loud delete pattern`.

It would be more reasonable to add `.loud ban pattern` then `!pattern`.

**Comment by BeefKnuckleback** [comment]
'XD' would be another one for the list.

**Comment by drobati** [comment]
NO YOU.

**Comment by drobati** [comment]
Oh I think we can close this too. @josiahp or @sshirokov
