### ISSUE TITLE
Louds can't emote hard enough

### ISSUE THREAD

**Issue by sshirokov** [desert-planet/hayt#175]
A bunch of symbols like `!?:()$` and friends are not included in the `loud.coffee` regex, so Hayt just yells without feeling.

I would like Hayt to yell a wider range of truly authentic emotions, often questioning, or explaining something in the process.

**Comment by sshirokov** [comment]
Hey, @skalnik -- I DID THIS FOR YOU, I DID THIS BECAUSE YOU TOLD ME TO, NOW FIX IT

**Comment by skalnik** [comment]
That regex lives here right now: https://github.com/desert-planet/hayt/blob/master/scripts/loud.coffee#L21

**Comment by sshirokov** [comment]
We have added `!` in https://github.com/desert-planet/hayt/pull/202 and no one noticed anything else going wrong. Closing until someone does.
