### ISSUE TITLE
LOUDS IGNORE ASTERISKS AND DOUBLE QUOTES

### ISSUE THREAD

**Issue by drobati** [desert-planet/hayt#205]
5:11 PM <skalnik> "THAT YOU VERY MUCHO MR.ROBOTO"
5:11 PM <skalnik> THANK*

5:12 PM <skalnik> both "s and *s are ignored by Hayt's louds

**Comment by sshirokov** [comment]
**THANKS FOR THE REPORT, SOMEONE SHOULD FIX THIS**

CC/ @justinwoo

**Comment by drobati** [comment]
@justinwoo A++++ thanks for helping out
