### ISSUE TITLE
AYP returned error

### ISSUE THREAD

**Issue by drobati** [desert-planet/hayt#221]
```
11:26 PM <devhost> .ayp
11:26 PM <@Hayt> devhost: What the hell is a JAY PEG?! Error: Woooops! Failed to upload: Error: read ECONNRESET
```

**Comment by sshirokov** [comment]
Yep, it sure did. 

S3 failed to connect, and looks like it's one of the few error handlers that actually work in AYP

**Comment by drobati** [comment]
So the issue is on their end?

**Comment by sshirokov** [comment]
This is a fact of life, not really an issue on anyone's end.
