### ISSUE TITLE
.AYP command enhancement request (nickname targeting)

### ISSUE THREAD

**Issue by n1ckn4m3** [desert-planet/hayt#65]
Request enhancement to .ayp command, allowing an irc nickname to be specified, causing the comic generation to begin with a chat line written by the target nickname.  If the word 'me' is used, use a line from the chat log written by the person who is requesting it's nickname as the first line of the comic.

**Comment by sshirokov** [comment]
It's been almost a year, and I'm almost certain this will almost never happen.

Also something about ruining the art of chance :trollface:
