### ISSUE TITLE
Rename repo to "Hayt"

### ISSUE THREAD

**Issue by skalnik** [desert-planet/hayt#97]
Since its moved to desert-planet, it would be for the best.

**Comment by Drewzar** [comment]
@sshirokov Can I get temporary admin access to test? 

![image](https://cloud.githubusercontent.com/assets/653446/7210308/999cb642-e505-11e4-9397-1155ed33da34.png)

**Comment by Drewzar** [comment]
nvm, doing this on my own org.

**Comment by Drewzar** [comment]
If you rename the repo the redirect still hold. 

See: 
https://github.com/drewzar/test-repo-please-ignore
and:
https://github.com/test-org-please-ignore/test-repo-please-ignore-lolol

**Comment by sshirokov** [comment]
Nice, nice, does git redirect correctly also?

**Comment by Drewzar** [comment]
How should I test it?

**Comment by sshirokov** [comment]
Can you still `git fetch` from the old remote?

**Comment by Drewzar** [comment]
![image](https://cloud.githubusercontent.com/assets/653446/7211226/bc994d2e-e50d-11e4-803a-ae5dce4e0169.png)

**Comment by sshirokov** [comment]
This is done. 

Good science work, science guy.
